name: "PR Comment Status"
description: "Updates PR comments with check status, removing old comments and adding failure comments if needed."

inputs:
  check_name:
    description: "Unique header string to identify this check's comments"
    type: string
    required: true

  failure_message:
    description: "The message body to post on failure"
    type: string
    required: true

  pr_id:
    description: "Issue ID of the pull request"
    required: true
    type: number

  check_status:
    description: "The passing status of the job (success or failure)"
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - name: "Find and remove failure comment on PR (if applicable)"
      uses: actions/github-script@v7
      env:
        PR_ID: ${{ inputs.pr_id }}
        BODY_HEADER: "${{ inputs.check_name }}"
      with:
        script: |
          const comments = await github.rest.issues.listComments({
            issue_number: process.env.PR_ID,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const botComments = comments.data.filter(comment =>
            comment.user.login === 'github-actions[bot]' &&
            comment.body.includes(process.env.BODY_HEADER)
          );

          for (const comment of botComments) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id,
            });
          }

    - name: "Comment on PR on failure (if applicable)"
      if: inputs.check_status == 'failure'
      uses: actions/github-script@v7
      env:
        PR_ID: ${{ inputs.pr_id }}
        COMMENT_BODY: "🚨 ${{ inputs.check_name }}\n\n${{ inputs.failure_message }}"
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: process.env.PR_ID,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.COMMENT_BODY
          });

    - name: "Set Completed Status"
      uses: HBK-MicroStrain-Internal/actions/pull-request-commit-check@main
      with:
        status: ${{ inputs.check_status }}
