name: "PR Comment Status"
description: "Updates PR comments with check status, removing old comments and adding failure comments if needed."

inputs:
  check_name:
    description: "Unique header string to identify this check's comments"
    type: string
    required: true

  failure_message:
    description: "The message body to post on failure"
    type: string
    required: true

  pr_id:
    description: "Issue ID of the pull request"
    required: true
    type: number

  check_status:
    description: "The passing status of the job (success or failure)"
    type: string
    required: true

  workflow_name:
    description: "The name of the initial calling workflow. Use github.workflow"
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: "Find and remove failure comment on PR (if applicable)"
      uses: actions/github-script@v7
      env:
        PR_ID: ${{ inputs.pr_id }}
        BODY_HEADER: "${{ inputs.check_name }}"
      with:
        script: |
          const comments = await github.rest.issues.listComments({
            issue_number: process.env.PR_ID,
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          const botComments = comments.data.filter(comment =>
            comment.user.login === 'github-actions[bot]' &&
            comment.body.includes(process.env.BODY_HEADER)
          );

          for (const comment of botComments) {
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: comment.id,
            });
          }

    - name: "Comment on PR on failure (if applicable)"
      if: inputs.check_status == 'failure'
      uses: actions/github-script@v7
      env:
        PR_ID: ${{ inputs.pr_id }}
        COMMENT_BODY: "🚨 ${{ inputs.check_name }}\n\n${{ inputs.failure_message }}"
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: process.env.PR_ID,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: process.env.COMMENT_BODY
          });

    - name: "Get Job Info"
      # Makes an environment variable with the full job name: $GITHUB_JOB_NAME
      uses: qoomon/actions--context@v5

    - name: "Fetch PR Head SHA"
      id: fetch-sha
      shell: bash
      run: |
        SHA=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ inputs.pr_id }}" \
          | jq -r .head.sha)

        echo "sha=$SHA" >> $GITHUB_OUTPUT

#    - name: "Print Existing Statuses"
#      uses: actions/github-script@v7
#      env:
#        PR_SHA: ${{ steps.fetch-sha.outputs.sha }}
#      with:
#        script: |
#          const statuses = await github.rest.repos.listCommitStatusesForRef({
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            ref: process.env.PR_SHA,
#          });
#
#          console.log(`Existing statuses for PR ${process.env.PR_SHA}:`);
#
#          for (const status of statuses.data) {
#            console.log(`- ${status.context}: ${status.state}`);
#          }

    - name: "Update Commit Check"
      uses: LouisBrunner/checks-action@v2.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: "${{ env.GITHUB_JOB_NAME }}"
        conclusion: ${{ inputs.check_status }}
        sha: ${{ steps.fetch-sha.outputs.sha }}

#    - name: "Update Commit Status"
#      if: ${{ github.event_name != 'pull_request' }}
#      uses: myrotvorets/set-commit-status-action@v2.0.1
#      with:
#        status: ${{ inputs.check_status }}
#        sha: ${{ steps.fetch-sha.outputs.sha }}
#        context: "${{ inputs.workflow_name }} / ${{ env.GITHUB_JOB_NAME }} (pull_request)"
#        targetUrl: "${{ env.GITHUB_JOB_HTML_URL }}?pr${{ inputs.pr_id }}"

#    - name: "Update Commit Status"
#      if: ${{ github.event_name != 'pull_request' }}
#      uses: actions/github-script@v7
#      env:
#        # Job name MUST match exactly with the event trigger
#        JOB_NAME: "${{ inputs.workflow_name }} / ${{ env.GITHUB_JOB_NAME }} (pull_request)"
#        PR_SHA: ${{ steps.fetch-sha.outputs.sha }}
#        STATUS: ${{ inputs.check_status }}
#      with:
#        script: |
#          await github.rest.repos.createCommitStatus({
#            owner: context.repo.owner,
#            repo: context.repo.repo,
#            sha: process.env.PR_SHA,
#            state: process.env.STATUS,
#            context: process.env.JOB_NAME,
#            description: process.env.STATUS === "success" ? "Check passed" : "Check failed"
#          });
