name: "PR Commit Check Status"
description: "Sets/Updates the check status of a commit for a pull request"

inputs:
  token:
    description: "The GitHub token to use for authentication"
    required: true
    type: string

  status:
    description: "Status of the check. 'success', 'failure', 'in_progress'"
    required: false
    type: string
    default: 'in_progress'

outputs:
  head_sha:
    description: "The HEAD commit SHA for the pull request"
    value: ${{ steps.head-sha.outputs.sha }}

  base_sha:
    description: "The BASE commit SHA for the pull request"
    value: ${{ steps.base-sha.outputs.sha }}

  pr_id:
    description: "The ID of the pull request"
    value: ${{ steps.pr-metadata.outputs.id }}

  pr_owner:
    description: "The owner of the pull request"
    value: ${{ steps.pr-metadata.outputs.owner }}

runs:
  using: "composite"
  steps:
    - name: "Get PR Metadata"
      id: pr-metadata
      shell: bash
      run: |
        id=0
        owner=""

        if [ "${{ github.event_name }}" = "pull_request" ]; then
          id=${{ github.event.pull_request.number }}
          owner="${{ github.event.pull_request.user.login }}"
        elif [ "${{ github.event_name }}" = "issue_comment" ] &&
             [ "${{ github.event.issue.pull_request }}" != "" ]; then
          id=${{ github.event.issue.number }}
          owner=${{ github.event.issue.user.login }}
        else
          echo "This action can only run for pull requests"
          exit 1
        fi

        echo "id=$id" >> $GITHUB_OUTPUT
        echo "owner=$owner" >> $GITHUB_OUTPUT

    - name: "Get HEAD Commit SHA"
      id: head-sha
      shell: bash
      run: |
        sha=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ steps.pr-metadata.outputs.id }}" \
          | jq -r .head.sha)

        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: "Get BASE Commit SHA"
      id: base-sha
      shell: bash
      run: |
        sha=$(curl -s -H "Authorization: token ${{ github.token }}" \
          "${{ github.api_url }}/repos/${{ github.repository }}/pulls/${{ steps.pr-metadata.outputs.id }}" \
          | jq -r .base.sha)

        echo "sha=$sha" >> $GITHUB_OUTPUT

    - name: "Get Job Info"
      # Makes an environment variable with the full job name: $GITHUB_JOB_NAME
      uses: qoomon/actions--context@v5

    - name: "Determine Status"
      id: status
      shell: bash
      run: |
        conclusion=""
        status="completed"

        if [ "${{ inputs.status }}" = "success" ]; then
          conclusion="success"
        elif [ "${{ inputs.status }}" = "failure" ]; then
          conclusion="failure"
        elif [ "${{ inputs.status }}" = "in_progress" ]; then
          status="in_progress"
        else
          conclusion="neutral"
        fi

        echo "conclusion=$conclusion" >> $GITHUB_OUTPUT
        echo "status=$status" >> $GITHUB_OUTPUT

    - name: "Set Commit Check Status"
      uses: actions/github-script@v7
      env:
        SHA: ${{ steps.head-sha.outputs.sha }}
        CHECK_NAME: ${{ env.GITHUB_JOB_NAME }}
        CONCLUSION: ${{ steps.status.outputs.conclusion }}
        STATUS: ${{ steps.status.outputs.status }}
      with:
        github-token: '${{ steps.app-token.outputs.token }}'
        script: |
          // Find any existing checks on the commit
          const { data: checks } = await github.rest.checks.listForRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: process.env.SHA
          });

          // Find this specific check
          const existing_check = checks.check_runs.find(
            r => r.name === process.env.CHECK_NAME
          );
          
          // Get the time of update/creation
          const time = new Date().toISOString();

          // Update this existing check
          if (existing_check) {
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: existing_check.id,
              status: process.env.STATUS,
              ...(process.env.STATUS === 'completed' ? {
                conclusion: process.env.CONCLUSION,
                completed_at: time
              } : {
                started_at: time
              })
            });
          }
          // Create a new check
          else
          {
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: process.env.CHECK_NAME,
              head_sha: process.env.SHA,
              status: process.env.STATUS,
              started_at: time
            });
          }
