name: 'Pull Request Checkbox Selection Check'
description: 'Check whether the checkbox in a pull request message body is checked'

inputs:
  checkbox_label:
    description: 'The label next to the checkbox'
    required: true

outputs:
  checked:
    description: 'Whether the checkbox is checked or not'
    value: ${{ steps.checkbox-state.outputs.checked }}

runs:
  using: "composite"
  steps:
    - name: 'Get Checkbox State'
      id: checkbox-state
      shell: bash
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
      run: |
        checked="false"
        
        # Debug the PR body for hidden characters
        echo "${PR_BODY}" | cat -A | grep -i "changelog release"
        
        # Only check if the event actor isn't a bot
        # Defaults to unchecked if it is a bot
        if [[ "${{ github.actor }}" != "github-actions[bot]" ]]; then
          pattern="- [x] ${{ inputs.checkbox_label }}"
  
          # Get a count of the existing checkbox search pattern
          # Prevents errors if the checkbox doesn't actually exist
          count=$(echo "${PR_BODY}" | grep -cF -- "${pattern}" || true)
  
          if [[ "${count}" -gt 0 ]]; then
            checked="true"
          fi
        fi

        echo "checked=${checked}" >> $GITHUB_OUTPUT
