name: Checkout
description: Checkout the repository with recursive submodules

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
