name: Archive Artifacts
description: Archive build artifacts
inputs:
  path:
    description: 'Path to the artifacts relative to the project root'
    default: 'packages/**'
  file_name:
    description: 'Artifact file name(s) or regex pattern with extension'
    default: '*'
  artifact_name:
    description: 'Fallback artifact name for the archiving step'
    required: true

runs:
  using: "composite"
  steps:
    - name: Calculate Artifact Name
      id: artifact-naming
      shell: bash
      run: |
        shopt -s nullglob
        files=(${{ github.workspace }}/${{ inputs.path }}/${{ inputs.file_name }})
        count=${#files[@]}
        if [ $count -eq 1 ]; then
          artifact_name=$(basename "${files[0]}")
        else
          artifact_name="${{ inputs.artifact_name }}"
        fi
        echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact-naming.outputs.artifact_name }}
        path: '${{ inputs.path }}/${{ inputs.file_name }}'
        if-no-files-found: error
