name: Archive Artifacts
description: Archive build artifacts
inputs:
  path:
    description: 'Path to the artifacts relative to the project root'
    default: 'packages/**'
  file_name:
    description: 'Artifact file name(s) or regex pattern with extension. Use comma to separate multiple patterns'
    default: '*'
  artifact_name:
    description: 'Fallback artifact name for the archiving step'
    required: true

runs:
  using: "composite"
  steps:
    - name: Determine Artifact Search Pattern
      id: artifact-pattern
      shell: bash
      run: |
        # 1. Convert comma to newline
        # 2. Prepend the directory to each line
        path_pattern=$(echo "${{ inputs.file_name }}" | tr ',' '\n' | sed "s|^|${{ inputs.path }}/|")

        # Generate a multi-line string
        {
          echo "path_patterns<<EOF"
          echo "$path_patterns"
          echo "EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Determine Artifact Name
      id: artifact-naming
      shell: bash
      run: |
        # Default no found matches to null instead of returning the search pattern
        shopt -s nullglob

        # Convert the multi-line string output back into a Bash array
        # This handles the globbing automatically
        mapfile -t patterns <<< "${{ steps.artifact-pattern.outputs.path_patterns }}"
        files=(${patterns[@]})

        # Get a file count
        count=${#files[@]}

        if [ $count -eq 1 ]; then
          # Only 1 file, use the file name
          artifact_name=$(basename "${files[0]}")
        else
          # Multiple files, use the provided artifact name
          artifact_name="${{ inputs.artifact_name }}"
        fi

        echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact-naming.outputs.artifact_name }}
        path:  ${{ steps.artifact-pattern.outputs.path_patterns }}
        if-no-files-found: error
